apiVersion: v1
kind: ServiceAccount
metadata:
  name: dap-controller
  namespace: dap-k8s-prototype
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dap-controller
  namespace: dap-k8s-prototype
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/proxy", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dap-controller
  namespace: dap-k8s-prototype
subjects:
  - kind: ServiceAccount
    name: dap-controller
    namespace: dap-k8s-prototype
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dap-controller

