apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dap-worker-keda
  namespace: dap-k8s-prototype
spec:
  scaleTargetRef:
    name: dap-worker
  pollingInterval: 10
  cooldownPeriod: 20
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 5
        scaleDown:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.dap-k8s-prototype.svc.cluster.local:9090
        metricName: dap_worker_queue_depth
        query: sum(queue_depth{namespace="dap-k8s-prototype"})
        threshold: "4"
